#!/bin/sh

# 05-date
# by throwaway96
# Licensed under GNU AGPL version 3 or later.
# https://github.com/throwaway96/webos1-bindca

if [ "$(date '+%Y')" -lt 2023 ]; then
	date --set '2023-12-05 00:00'
fi

# vim: noet:ts=8:sw=8
